services:
  - type: web
    name: aletheia-backend
    env: docker
    plan: free
    dockerfilePath: backend/Dockerfile
    region: oregon
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_INDEX
        value: aletheia
      - key: NEO4J_URI
        sync: false
      - key: NEO4J_USER
        sync: false
      - key: NEO4J_PASS
        sync: false
      - key: DATABASE_URL
        sync: false

